name: ProgrammEngineering18
channels:
  - defaults
dependencies:
  - black=24.2.0
  - cfgv=3.4.0
  - flake8=7.0.0
  - isort=5.13.2
  - packaging=23.2
  - pip=23.3.1
  - pre-commit=3.6.2
  - python=3.12.0
  - PyYAML=6.0.1
